version: '3.8'

services:
  # Service de l'application pharmaSen
  api:
    build:
      context: .
      target: production
    container_name: pharmasen-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
